In [ ]:
!git clone --branch dawid/transformers https://github.com/dawidsroczyk/Deep-Learning.git
!mv Deep-Learning/transformers/* .
!gdown 1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
!gdown 1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
!gdown 1GMYLTBi2J0z8tFkDe0sHvw284C4D9Ru5
!mkdir models
!mkdir output

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 2404, done.
remote: Counting objects: 100% (945/945), done.
remote: Compressing objects: 100% (515/515), done.
remote: Total 2404 (delta 496), reused 873 (delta 429), pack-reused 1459 (from 3)
Receiving objects: 100% (2404/2404), 98.03 MiB | 14.11 MiB/s, done.
Resolving deltas: 100% (1135/1135), done.
Downloading...
From (original): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
From (redirected): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L&confirm=t&uuid=6f7eba0f-3025-4580-bcd5-2a4007f84b52
To: /content/test.pt
100% 321M/321M [00:06<00:00, 52.1MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
From (redirected): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc&confirm=t&uuid=e065fd17-2603-4578-b784-edfa88ca6248
To: /content/train.pt
100% 1.28G/1.28G [00:07<00:00, 175MB/s]
Downloading...
From: https://drive.google.com/uc

In [ ]:
from ast_11_sigmoid_batch_padding import train_ast

# Weight Decay

In [ ]:
!mkdir models_wd0_1
!mkdir output_wd0_1
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.1,
    model_path='models_wd0_1',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_1',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 146.5688 | Train Acc: 0.4370
Test Acc: 0.1970
Train Confusion Matrix:
 [[1866   16    3    0   26    1    3    2    2    0    1]
 [  32  831   70   94   68   56  235   44   28  252  191]
 [  35   58  714  110  299  336   89   53   90   40   61]
 [  42  109   67  649  224   91   88  124  271   29  193]
 [  42   65  250  200  862  141   74   60  109   21   69]
 [  33   59  254   69  151  946   89  128   85   29   57]
 [  44  243   79   96   76   77  706   99   51  235  187]
 [  51  103  103  163  104  243  129  742  144   22  100]
 [  45   97  102  291  164  131   80  120  621   29  217]
 [  49  365  104   94   67   94  327   76   45  500  161]
 [  30  219   61  182  105   55  232   93  139  104  680]]
Test Confusion Matrix:
 [[456   0   0   0   0   0   0   0   0   0   0  24]
 [  5   9   0   0   0   0   0   0   0   0   0 462]
 [  5   0   1   0   2   1   0   1   0   0   0 462]
 [  8   0   0   1   0 

In [ ]:
!mkdir models_wd0_01
!mkdir output_wd0_01
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.01,
    model_path='models_wd0_01',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_01',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 146.5492 | Train Acc: 0.4373
Test Acc: 0.1972
Train Confusion Matrix:
 [[1865   16    4    0   26    1    3    2    2    0    1]
 [  31  835   69   97   67   55  233   44   28  251  191]
 [  37   58  712  110  302  334   89   52   90   41   60]
 [  42  107   67  651  224   90   91  123  271   29  192]
 [  41   62  250  201  864  139   75   60  108   22   71]
 [  33   58  251   72  147  945   90  130   87   30   57]
 [  44  241   80   97   77   77  709   99   51  235  183]
 [  51  106  101  160  106  242  125  745  146   23   99]
 [  46   97  105  287  161  131   81  125  618   28  218]
 [  49  363  106   96   69   92  324   75   45  501  162]
 [  29  222   62  181  105   54  234   94  140  102  677]]
Test Confusion Matrix:
 [[456   0   0   0   0   0   0   0   0   0   0  24]
 [  5   9   0   0   0   0   0   0   0   0   0 462]
 [  5   0   1   0   2   1   0   1   0   0   0 462]
 [  8   0   0   4   0 

In [ ]:
!mkdir models_wd0_2
!mkdir output_wd0_2
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.2,
    model_path='models_wd0_2',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_2',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 146.5736 | Train Acc: 0.4371
Test Acc: 0.1969
Train Confusion Matrix:
 [[1866   16    4    0   26    1    3    2    1    0    1]
 [  32  831   69   94   68   57  232   48   29  250  191]
 [  37   59  707  109  302  339   90   54   88   40   60]
 [  42  109   69  650  229   88   89  120  274   28  189]
 [  41   64  254  197  865  141   73   57  108   21   72]
 [  33   57  251   70  149  947   92  129   85   31   56]
 [  44  240   80   95   76   76  710   98   52  237  185]
 [  52  102  102  156  110  240  125  745  148   25   99]
 [  46   97  102  294  163  128   81  124  617   29  216]
 [  49  360  105   94   70   92  331   77   45  502  157]
 [  29  221   62  183  104   55  232   93  140  103  678]]
Test Confusion Matrix:
 [[457   0   0   0   0   0   0   0   0   0   0  23]
 [  5   9   0   0   0   0   0   0   0   0   0 462]
 [  6   0   1   0   2   1   0   1   0   0   0 461]
 [  8   0   0   1   0 

In [ ]:
!mkdir models_wd0_15
!mkdir output_wd0_15
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.15,
    model_path='models_wd0_15',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_15',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 146.5592 | Train Acc: 0.4373
Test Acc: 0.1976
Train Confusion Matrix:
 [[1866   16    3    0   26    1    3    2    2    0    1]
 [  32  831   70   95   69   56  235   43   28  251  191]
 [  35   59  716  110  296  336   88   53   90   40   62]
 [  42  108   67  646  227   91   88  124  272   29  193]
 [  41   63  250  200  868  139   73   60  107   21   71]
 [  33   57  251   70  150  946   91  131   84   31   56]
 [  44  244   80   96   76   76  711   97   50  232  187]
 [  51  102  104  164  105  240  126  746  143   22  101]
 [  45   98  105  288  164  133   81  122  618   28  215]
 [  48  365  106   93   68   93  331   75   44  498  161]
 [  30  220   62  185  105   54  234   93  140  101  676]]
Test Confusion Matrix:
 [[455   0   0   0   0   0   0   0   0   0   0  25]
 [  4   9   0   0   0   0   0   0   0   0   0 463]
 [  5   0   1   0   2   1   0   1   0   0   0 462]
 [  7   0   0   2   0 

# Learning Rate

In [ ]:
!mkdir models_lr0_000005
!mkdir output_lr0_000005
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=0.000005,
    weight_decay=0.1,
    model_path='models_lr0_000005',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_000005',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 158.4106 | Train Acc: 0.3897
Test Acc: 0.1865
Train Confusion Matrix:
 [[1859   23    0    2   29    1    3    0    2    0    1]
 [  57  715   96   98   70   41  211   69   42  300  202]
 [  55   88  610   96  272  385   79   61  103   70   66]
 [  62  153   87  580  241   86   84  162  244   35  153]
 [  72  110  265  176  737  149   78   58  141   37   70]
 [  59   91  183   80  161  941  102  107   97   26   53]
 [  74  251   97   94   76   54  562  124   73  292  196]
 [  70  153   92  166  111  273  147  594  130   47  121]
 [  63  126  124  259  186  148   91  156  508   37  199]
 [  71  343  114   97   92   85  289   77   42  518  154]
 [  44  298   75  164  135   54  255  120  114  136  505]]
Test Confusion Matrix:
 [[438   0   0   0   0   0   0   0   0   0   0  42]
 [  8   1   0   0   0   0   0   0   0   0   0 467]
 [  9   0   0   0   0   1   0   0   0   0   0 462]
 [  9   1   0   0   0 

In [ ]:
!mkdir models_lr0_0000025
!mkdir output_lr0_0000025
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=0.0000025,
    weight_decay=0.1,
    model_path='models_lr0_0000025',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_0000025',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 173.4638 | Train Acc: 0.3266
Test Acc: 0.1512
Train Confusion Matrix:
 [[1828   58    0    0   31    3    0    0    0    0    0]
 [  99  589  120  101   74   45  249   56   54  332  182]
 [  80  109  458   96  224  440   76   67  132  102  101]
 [  95  208  124  418  274  128   83  157  205   61  134]
 [  93  131  288  207  547  182   74   66  163   43   99]
 [  80  109  148   84  144  907   88   92  132   42   74]
 [  94  297  115  101   90   53  378  113  113  315  224]
 [ 107  230  105  143  150  311  131  375  133   60  159]
 [  87  153  160  180  203  204   77  171  431   46  185]
 [ 110  303  123   86  104   92  235   78   63  527  161]
 [  75  311  103  150  173   56  248  105  122  202  355]]
Test Confusion Matrix:
 [[355   0   0   0   0   0   0   0   0   0   0 125]
 [ 42   0   0   0   0   0   0   0   0   0   0 434]
 [ 32   0   0   0   0   0   0   0   0   0   0 440]
 [ 49   0   0   0   0 

In [ ]:
!mkdir models_lr0_000001
!mkdir output_lr0_000001
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=0.000001,
    weight_decay=0.1,
    model_path='models_lr0_000001',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_000001',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 193.6705 | Train Acc: 0.2564
Test Acc: 0.1090
Train Confusion Matrix:
 [[1718  120    0    1   69   12    0    0    0    0    0]
 [ 160  478   65  109   74   89  155   86   66  390  229]
 [ 103  184  183  102  110  594   64  123  154  171   97]
 [ 148  274   74  319  150  219   85  181  132  134  171]
 [ 135  216  173  194  253  323   92  151  143   95  118]
 [ 120  162   59   66   96  807   71   96  195   77  151]
 [ 143  306   55  132   78   60  160  141  147  359  312]
 [ 163  333   48  115  103  359   70  208  158  101  246]
 [ 111  214   93  151  113  290   72  231  284   90  248]
 [ 132  322   76   70   97  120  106  115  111  511  222]
 [ 126  308   52  141  105   85  155  153  109  238  428]]
Test Confusion Matrix:
 [[143   0   0   0   0   0   0   0   0   0   0 337]
 [ 48   0   0   0   0   0   0   0   0   0   0 428]
 [ 36   0   0   0   0   0   0   0   0   0   0 436]
 [ 65   0   0   0   0 

In [ ]:
!mkdir models_lr0_0000005
!mkdir output_lr0_0000005
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=0.0000005,
    weight_decay=0.1,
    model_path='models_lr0_0000005',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_0000005',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 211.1864 | Train Acc: 0.2126
Test Acc: 0.0955
Train Confusion Matrix:
 [[1508  200    0    0  184   28    0    0    0    0    0]
 [ 149  407   45  181   70  128   24   87   49  388  373]
 [ 103  242   73  102   62  518   22  111  174  262  216]
 [ 156  286   41  300   80  215   34  161   93  185  336]
 [ 138  268   74  188  132  329   43  141   95  179  306]
 [ 126  197   32   59   76  621   41   94  232  127  295]
 [ 148  321   23  212   69   66   19  133  131  297  474]
 [ 159  277   21  164   84  321   21  154  204  145  354]
 [ 104  245   53  175   71  301   19  205  181  105  438]
 [ 143  316   45  118   77  126   14  103  135  472  333]
 [ 141  290   41  191   66  114   26  139   87  237  568]]
Test Confusion Matrix:
 [[ 25   0   0   0   0   0   0   0   0   0   0 455]
 [ 10   0   0   0   0   0   0   0   0   0   0 466]
 [ 10   0   0   0   0   0   0   0   0   0   0 462]
 [  8   0   0   0   0 