In [ ]:
!git clone --branch dawid/transformers https://github.com/dawidsroczyk/Deep-Learning.git
!mv Deep-Learning/transformers/* .
!gdown 1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
!gdown 1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
!gdown 1GMYLTBi2J0z8tFkDe0sHvw284C4D9Ru5
!rm unknown.pt
!gdown 1hq1OAnSpFCsRJi3E3clpNLfDxhOHpE4H
!mkdir models
!mkdir output

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 2565, done.
remote: Counting objects: 100% (1106/1106), done.
remote: Compressing objects: 100% (591/591), done.
remote: Total 2565 (delta 590), reused 1024 (delta 513), pack-reused 1459 (from 3)
Receiving objects: 100% (2565/2565), 98.68 MiB | 27.10 MiB/s, done.
Resolving deltas: 100% (1229/1229), done.
Downloading...
From (original): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
From (redirected): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L&confirm=t&uuid=8e61bba1-3755-4f97-87ef-05d88dd6e98e
To: /content/test.pt
100% 321M/321M [00:04<00:00, 69.6MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
From (redirected): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc&confirm=t&uuid=6a5c4333-46f4-4a94-b072-10b0cc2793f7
To: /content/train.pt
100% 1.28G/1.28G [00:16<00:00, 77.6MB/s]
Downloading...
From: https://drive.google.co

In [ ]:
from batch_ast import train_ast

# Batch Size

In [ ]:
!mkdir models_bs1
!mkdir output_bs1
train_ast(
    num_epochs=30,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs1',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs1',
    random_seed=123,
    batch_size=1
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


Streaming output truncated to the last 5000 lines.
16100 / 22782
16200 / 22782
16300 / 22782
16400 / 22782
16500 / 22782
16600 / 22782
16700 / 22782
16800 / 22782
16900 / 22782
17000 / 22782
17100 / 22782
17200 / 22782
17300 / 22782
17400 / 22782
17500 / 22782
17600 / 22782
17700 / 22782
17800 / 22782
17900 / 22782
18000 / 22782
18100 / 22782
18200 / 22782
18300 / 22782
18400 / 22782
18500 / 22782
18600 / 22782
18700 / 22782
18800 / 22782
18900 / 22782
19000 / 22782
19100 / 22782
19200 / 22782
19300 / 22782
19400 / 22782
19500 / 22782
19600 / 22782
19700 / 22782
19800 / 22782
19900 / 22782
20000 / 22782
20100 / 22782
20200 / 22782
20300 / 22782
20400 / 22782
20500 / 22782
20600 / 22782
20700 / 22782
20800 / 22782
20900 / 22782
21000 / 22782
21100 / 22782
21200 / 22782
21300 / 22782
21400 / 22782
21500 / 22782
21600 / 22782
21700 / 22782
21800 / 22782
21900 / 22782
22000 / 22782
22100 / 22782
22200 / 22782
22300 / 22782
22400 / 22782
22500 / 22782
22600 / 22782
22700 / 22782
Epoch 11/30

In [ ]:
!mkdir models_bs2
!mkdir output_bs2
train_ast(
    num_epochs=30,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs2',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs2',
    random_seed=123,
    batch_size=2
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 11391
100 / 11391
200 / 11391
300 / 11391
400 / 11391
500 / 11391
600 / 11391
700 / 11391
800 / 11391
900 / 11391
1000 / 11391
1100 / 11391
1200 / 11391
1300 / 11391
1400 / 11391
1500 / 11391
1600 / 11391
1700 / 11391
1800 / 11391
1900 / 11391
2000 / 11391
2100 / 11391
2200 / 11391
2300 / 11391
2400 / 11391
2500 / 11391
2600 / 11391
2700 / 11391
2800 / 11391
2900 / 11391
3000 / 11391
3100 / 11391
3200 / 11391
3300 / 11391
3400 / 11391
3500 / 11391
3600 / 11391
3700 / 11391
3800 / 11391
3900 / 11391
4000 / 11391
4100 / 11391
4200 / 11391
4300 / 11391
4400 / 11391
4500 / 11391
4600 / 11391
4700 / 11391
4800 / 11391
4900 / 11391
5000 / 11391
5100 / 11391
5200 / 11391
5300 / 11391
5400 / 11391
5500 / 11391
5600 / 11391
5700 / 11391
5800 / 11391
5900 / 11391
6000 / 11391
6100 / 11391
6200 / 11391
6300 / 11391
6400 / 11391
6500 / 11391
6600 / 11391
6700 / 11391
6800 / 11391
6900 / 11391
7000 / 11391
7100 / 11391
7200 / 11391
7300 / 11391
7400 / 11391
7500 / 11391
7600 / 11391
7700 / 1139

# Weight Decay

In [ ]:
!mkdir models_wd0_1
!mkdir output_wd0_1
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.1,
    model_path='models_wd0_1',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_1',
    random_seed=123,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1200.7660 | Train Acc: 0.4113
Test Acc: 0.5007
Train Confusion Matrix:
 [[1882    3    1    1    7    1    0    0    3    0    2   20]
 [  39  780   43  106   49   45  170   98   53  261  163   94]
 [  33   58  701   76  280  332   56   71  104   92   36   46]
 [  28   88   68  686  215   52   67   91  249   66  163  114]
 [  40   44  209  165  879  100   54   66  145   41   47  103]
 [  45   47  227   71  128  958   67  130   67   59   23   78]
 [  44  153   62   69   72   82  703   92   55  315  170   76]
 [  55   88   91  105   83  191  106  751  114   83  122  115]
 [  32   76  118  313  155  116   42  131  558   53  192  111]
 [  33  287   90   58   65   90  325   77   51  569  138   99]
 [  41  166   52  170  104   40  146   99  137  164  650  131]
 [  44  138  116  213  193  132  168  147  205  106  204  254]]
Test Confusion Matrix:
 [[469   0  10   0   0   1   0   0   0   0   0 

In [ ]:
!mkdir models_wd0_15
!mkdir output_wd0_15
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.15,
    model_path='models_wd0_15',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_15',
    random_seed=123,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1199.8215 | Train Acc: 0.4116
Test Acc: 0.4982
Train Confusion Matrix:
 [[1880    3    1    2    7    1    0    0    2    1    2   21]
 [  40  784   45   98   49   45  166  101   52  257  168   96]
 [  33   56  706   77  280  331   50   73  105   93   34   47]
 [  28   84   67  687  220   52   72   90  246   64  162  115]
 [  40   44  210  165  875  102   56   64  146   41   45  105]
 [  45   47  225   71  125  967   70  124   68   59   25   74]
 [  45  155   61   67   75   83  701   94   55  308  176   73]
 [  55   91   91  107   83  190  104  749  114   86  124  110]
 [  31   74  117  314  156  118   42  137  552   52  195  109]
 [  33  285   91   57   66   93  322   80   50  567  135  103]
 [  41  164   49  167  108   38  148  102  137  160  655  131]
 [  42  138  113  211  191  135  165  147  209  109  205  255]]
Test Confusion Matrix:
 [[469   0  10   0   0   1   0   0   0   0   0 

In [ ]:
!mkdir models_wd0_01
!mkdir output_wd0_01
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.01,
    model_path='models_wd0_01',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_01',
    random_seed=123,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1200.0814 | Train Acc: 0.4129
Test Acc: 0.4967
Train Confusion Matrix:
 [[1884    3    0    1    5    1    0    0    2    1    2   21]
 [  39  775   44  100   49   47  174   99   54  259  158  103]
 [  34   59  711   74  277  323   54   71  103   96   35   48]
 [  28   86   65  694  220   49   66   94  244   63  163  115]
 [  40   43  206  170  883  103   55   64  142   39   47  101]
 [  43   47  229   68  126  957   69  134   67   60   24   76]
 [  45  151   64   70   69   83  714   89   56  311  166   75]
 [  54   94   91  107   81  192  102  749  117   86  119  112]
 [  33   76  118  312  149  118   45  133  561   50  195  107]
 [  32  296   92   59   65   90  313   75   49  573  133  105]
 [  40  171   52  173  104   36  147  102  140  161  655  119]
 [  44  140  117  217  189  132  168  149  204  109  200  251]]
Test Confusion Matrix:
 [[469   0   7   0   0   4   0   0   0   0   0 

In [ ]:
!mkdir models_wd0_2
!mkdir output_wd0_2
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.2,
    model_path='models_wd0_2',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_wd0_2',
    random_seed=123,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1199.9802 | Train Acc: 0.4130
Test Acc: 0.4998
Train Confusion Matrix:
 [[1881    3    1    2    8    1    0    0    1    1    2   20]
 [  39  788   43  100   48   45  176   98   49  252  162  101]
 [  34   61  706   75  278  327   54   71  104   94   34   47]
 [  27   89   62  693  216   53   68   91  247   65  165  111]
 [  40   43  210  166  882  102   54   66  145   38   45  102]
 [  42   47  229   68  124  959   69  134   65   59   24   80]
 [  45  155   63   68   68   80  715   97   57  306  162   77]
 [  54   88   91  103   82  193  106  745  115   84  129  114]
 [  35   76  115  310  149  115   45  126  568   49  193  116]
 [  33  288   95   59   65   91  323   76   49  572  131  100]
 [  41  174   50  166  105   38  141  104  142  167  644  128]
 [  42  137  115  216  190  132  168  150  204  109  202  255]]
Test Confusion Matrix:
 [[469   0  10   0   0   1   0   0   0   0   0 

# Learning Rate

In [ ]:
!mkdir models_lr0_000005
!mkdir output_lr0_000005
train_ast(
    num_epochs=50,
    lr=0.000005,
    weight_decay=0.1,
    model_path='models_lr0_000005',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_000005',
    random_seed=987,
    batch_size=32
)

mkdir: cannot create directory ‘models_lr0_000005’: File exists
mkdir: cannot create directory ‘output_lr0_000005’: File exists


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1253.0626 | Train Acc: 0.3924
Test Acc: 0.4844
Train Confusion Matrix:
 [[1873    3   19    2    8    1    0    1    2    0    5    6]
 [  44  701   42  103   43   45  174   73   41  315  171  149]
 [  36   56  719   71  257  277   68  105   74   72   48  102]
 [  68  125   49  532  223   58   85  132  271   54  157  133]
 [  50   53  247  172  755  106   52   73  135   25   63  162]
 [  45   58  209   71  105  909   72  155   87   49   46   94]
 [  39  160   55   83   50   43  782   72   43  256  184  126]
 [  62  107   82  136   84  233   94  656  129   74  110  137]
 [  33   82   84  259  167  113   68  153  541   45  220  132]
 [  39  295  100   69   32   84  289   72   35  587  148  132]
 [  43  185   35  136   69   39  220  125  154  142  612  140]
 [  48  177  112  168  187  109  190  160  176  102  219  272]]
Test Confusion Matrix:
 [[478   0   1   0   0   0   0   0   0   1   0 

In [ ]:
!mkdir models_lr0_0000025
!mkdir output_lr0_0000025
train_ast(
    num_epochs=50,
    lr=0.0000025,
    weight_decay=0.1,
    model_path='models_lr0_0000025',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_0000025',
    random_seed=987,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1367.0381 | Train Acc: 0.3436
Test Acc: 0.4340
Train Confusion Matrix:
 [[1852    6   25    3    4    0    0    0    0    0   16   14]
 [  72  552   44  120   25   47  220   69   59  306  192  195]
 [  52   70  653   80  179  280   85  120  121   54   57  134]
 [  84  137   68  478  207   87   95  126  259   60  123  163]
 [  72   61  269  175  551  138   69   89  178   28   61  202]
 [  54   68  245   79   85  783   74  155  128   36   46  147]
 [  58  191   70   92   28   42  686   54   57  236  200  179]
 [  80  137   90  141   85  231  125  479  124   99  140  173]
 [  46   94  112  212  166  128   96  171  498   54  178  142]
 [  66  253  110   86   34   81  302   53   40  516  171  170]
 [  62  180   58  121   69   36  279  111  156  157  461  210]
 [  69  174  101  174  145  107  167  160  207   76  221  319]]
Test Confusion Matrix:
 [[479   0   0   0   0   0   0   0   0   1   0 

In [ ]:
!mkdir models_lr0_000001
!mkdir output_lr0_000001
train_ast(
    num_epochs=50,
    lr=0.000001,
    weight_decay=0.1,
    model_path='models_lr0_000001',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_000001',
    random_seed=987,
    batch_size=32
)

mkdir: cannot create directory ‘models_lr0_000001’: File exists
mkdir: cannot create directory ‘output_lr0_000001’: File exists


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1522.1157 | Train Acc: 0.2696
Test Acc: 0.3411
Train Confusion Matrix:
 [[1796   19   51    0    1    0    0    0    0    0   40   13]
 [ 115  355  110  136   20   55  224   72   86  303  207  218]
 [  93   62  560   92   92  363   87  182  151   40   33  130]
 [ 129  160  110  342  189  143   95  180  223   53   85  178]
 [ 119   67  318  177  305  194   82  155  220   10   37  209]
 [  95   75  241  115   58  657   78  194  175   20   44  148]
 [ 115  177  133  124   13   63  483   78   90  233  176  208]
 [ 117  148  128  152   67  262  136  256  140  158  154  186]
 [  84  109  161  169  144  148  115  212  444   64   74  173]
 [ 107  190  179   89   15  105  267   71   74  397  170  218]
 [ 103  181  119  131   57   67  300   83  181  180  252  246]
 [ 137  196  157  162   91  121  165  130  228   87  152  294]]
Test Confusion Matrix:
 [[476   0   0   0   0   0   0   0   0   0   0 

In [ ]:
!mkdir models_lr0_0000005
!mkdir output_lr0_0000005
train_ast(
    num_epochs=50,
    lr=0.0000005,
    weight_decay=0.1,
    model_path='models_lr0_000005',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_lr0_0000005',
    random_seed=987,
    batch_size=32
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1621.6606 | Train Acc: 0.2182
Test Acc: 0.2898
Train Confusion Matrix:
 [[1727   42  116    0    1    0    0    5    0    0   26    3]
 [ 158  229  167  163   24   93  143   97  114  288  271  154]
 [ 125   69  427   88   34  386   54  334  180   45   50   93]
 [ 165  121  200  320  119  158   53  294  181   61  107  108]
 [ 142  103  342  180  135  238   38  275  223   15   52  150]
 [ 142   87  269  116   22  508   49  329  181   23   69  105]
 [ 152  135  178  157   20   78  204  138  123  246  300  162]
 [ 157  118  152  159   59  252  101  258  152  186  166  144]
 [ 121  122  215  139   90  173   84  313  378   71   61  130]
 [ 151  139  226   90   10  128  171  123   93  314  257  180]
 [ 132  161  233  148   52   68  161  133  200  175  255  182]
 [ 179  172  217  157   70  123  104  203  247  109  123  216]]
Test Confusion Matrix:
 [[467   0   0   0   0   0   0   0   0   0   0 