In [ ]:
!git clone --branch dawid/transformers https://github.com/dawidsroczyk/Deep-Learning.git
!mv Deep-Learning/transformers/* .
!gdown 1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
!gdown 1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
!gdown 1GMYLTBi2J0z8tFkDe0sHvw284C4D9Ru5
!mkdir models
!mkdir output

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 2313, done.
remote: Counting objects: 100% (854/854), done.
remote: Compressing objects: 100% (470/470), done.
remote: Total 2313 (delta 443), reused 789 (delta 383), pack-reused 1459 (from 3)
Receiving objects: 100% (2313/2313), 97.86 MiB | 17.44 MiB/s, done.
Resolving deltas: 100% (1082/1082), done.
Downloading...
From (original): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
From (redirected): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L&confirm=t&uuid=06181236-0192-4a96-8ac3-49056a042013
To: /content/test.pt
100% 321M/321M [00:05<00:00, 53.9MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
From (redirected): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc&confirm=t&uuid=d4743184-2b5a-4d05-a36e-0539c04b8917
To: /content/train.pt
100% 1.28G/1.28G [00:21<00:00, 59.5MB/s]
Downloading...
From: https://drive.google.com/u

In [ ]:
from ast_11_sigmoid_batch_padding import train_ast

In [ ]:
!rm -rf models
!rm -rf output
!mkdir models
!mkdir output

In [ ]:
!mkdir models_bs1
!mkdir output_bs1
train_ast(
    num_epochs=30,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs1',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs1',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=1
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


Streaming output truncated to the last 5000 lines.
--------------------------------------------------
0 / 20862
100 / 20862
200 / 20862
300 / 20862
400 / 20862
500 / 20862
600 / 20862
700 / 20862
800 / 20862
900 / 20862
1000 / 20862
1100 / 20862
1200 / 20862
1300 / 20862
1400 / 20862
1500 / 20862
1600 / 20862
1700 / 20862
1800 / 20862
1900 / 20862
2000 / 20862
2100 / 20862
2200 / 20862
2300 / 20862
2400 / 20862
2500 / 20862
2600 / 20862
2700 / 20862
2800 / 20862
2900 / 20862
3000 / 20862
3100 / 20862
3200 / 20862
3300 / 20862
3400 / 20862
3500 / 20862
3600 / 20862
3700 / 20862
3800 / 20862
3900 / 20862
4000 / 20862
4100 / 20862
4200 / 20862
4300 / 20862
4400 / 20862
4500 / 20862
4600 / 20862
4700 / 20862
4800 / 20862
4900 / 20862
5000 / 20862
5100 / 20862
5200 / 20862
5300 / 20862
5400 / 20862
5500 / 20862
5600 / 20862
5700 / 20862
5800 / 20862
5900 / 20862
6000 / 20862
6100 / 20862
6200 / 20862
6300 / 20862
6400 / 20862
6500 / 20862
6600 / 20862
6700 / 20862
6800 / 20862
6900 / 20862


In [ ]:
!zip -r output_bs1.zip output_bs1/*

In [ ]:
!mkdir models_bs2
!mkdir output_bs2
train_ast(
    num_epochs=30,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs2',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs2',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=2
)

mkdir: cannot create directory ‘models_bs2’: File exists
mkdir: cannot create directory ‘output_bs2’: File exists
{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 10431
100 / 10431
200 / 10431
300 / 10431
400 / 10431
500 / 10431
600 / 10431
700 / 10431
800 / 10431
900 / 10431
1000 / 10431
1100 / 10431
1200 / 10431
1300 / 10431
1400 / 10431
1500 / 10431
1600 / 10431
1700 / 10431
1800 / 10431
1900 / 10431
2000 / 10431
2100 / 10431
2200 / 10431
2300 / 10431
2400 / 10431
2500 / 10431
2600 / 10431
2700 / 10431
2800 / 10431
2900 / 10431
3000 / 10431
3100 / 10431
3200 / 10431
3300 / 10431
3400 / 10431
3500 / 10431
3600 / 10431
3700 / 10431
3800 / 10431
3900 / 10431
4000 / 10431
4100 / 10431
4200 / 10431
4300 / 10431
4400 / 10431
4500 / 10431
4600 / 10431
4700 / 10431
4800 / 10431
4900 / 10431
5000 / 10431
5100 / 10431
5200 / 10431
5300 / 10431
5400 / 10431
5500 / 10431
5600 / 10431
5700 / 10431
5800 / 10431
5900 / 10431
6000 / 10431
6100 / 10431
6200 / 10431
6300 / 10431
6400 / 10431
6500 / 10431
6600 / 10431
6700 / 10431
6800 / 10431
6900 / 10431
7000 / 10431
7100 / 10431
7200 / 10431
7300 / 10431
7400 / 10431
7500 / 10431
7600 / 10431
7700 / 1043

In [ ]:
train_ast(
    num_epochs=30,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=4
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 5216
100 / 5216
200 / 5216
300 / 5216
400 / 5216
500 / 5216
600 / 5216
700 / 5216
800 / 5216
900 / 5216
1000 / 5216
1100 / 5216
1200 / 5216
1300 / 5216
1400 / 5216
1500 / 5216
1600 / 5216
1700 / 5216
1800 / 5216
1900 / 5216
2000 / 5216
2100 / 5216
2200 / 5216
2300 / 5216
2400 / 5216
2500 / 5216
2600 / 5216
2700 / 5216
2800 / 5216
2900 / 5216
3000 / 5216
3100 / 5216
3200 / 5216
3300 / 5216
3400 / 5216
3500 / 5216
3600 / 5216
3700 / 5216
3800 / 5216
3900 / 5216
4000 / 5216
4100 / 5216
4200 / 5216
4300 / 5216
4400 / 5216
4500 / 5216
4600 / 5216
4700 / 5216
4800 / 5216
4900 / 5216
5000 / 5216
5100 / 5216
5200 / 5216
Epoch 1/30
Train Loss: 1031.4631 | Train Acc: 0.5032
Test Acc: 0.3330
Train Confusion Matrix:
 [[1866   12    1    6    7   12    4    5    2    1    4]
 [  34 1004   41   39   45   35  145   96   34  292  136]
 [  35   59  807   42  308  342   47   95   61   54   35]
 [  29   85   47  800  192   34   76  121  246   36  221]
 [  43   49  228  151 1047   62   47   72   83   

In [ ]:
train_ast(
    num_epochs=30,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output',
    random_seed=987,
    unknown_threshold=0.8,
    batch_size=8
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/ast_11_sigmoid_batch_padding.py:206: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 2608
100 / 2608
200 / 2608
300 / 2608
400 / 2608
500 / 2608
600 / 2608
700 / 2608
800 / 2608
900 / 2608
1000 / 2608
1100 / 2608
1200 / 2608
1300 / 2608
1400 / 2608
1500 / 2608
1600 / 2608
1700 / 2608
1800 / 2608
1900 / 2608
2000 / 2608
2100 / 2608
2200 / 2608
2300 / 2608
2400 / 2608
2500 / 2608
2600 / 2608
Epoch 1/30
Train Loss: 523.7447 | Train Acc: 0.5001
Test Acc: 0.3172
Train Confusion Matrix:
 [[1874    6    1    7   11    2    4    6    3    3    3]
 [  43  994   46   52   56   28  132   76   35  280  159]
 [  40   57  814   44  329  320   52   80   66   48   35]
 [  38   85   43  763  191   38   72  128  263   41  225]
 [  45   65  224  143 1065   64   44   64   86   35   58]
 [  41   61  266   35  114 1052   47  166   42   42   34]
 [  38  192   66   65   74   37  835   74   52  283  177]
 [  45  112   87  121   90  183  111  891  151   49   64]
 [  49   99   78  268  147   69   63  173  683   41  227]
 [  44  377   68   45   73   55  314   68   43  649  146]
 [  42  192   

In [ ]:
!zip -r output_bs16.zip output/*

  adding: output/epoch_10_confusion_matrices.json (deflated 89%)
  adding: output/epoch_11_confusion_matrices.json (deflated 89%)
  adding: output/epoch_12_confusion_matrices.json (deflated 89%)
  adding: output/epoch_13_confusion_matrices.json (deflated 89%)
  adding: output/epoch_14_confusion_matrices.json (deflated 89%)
  adding: output/epoch_15_confusion_matrices.json (deflated 90%)
  adding: output/epoch_16_confusion_matrices.json (deflated 90%)
  adding: output/epoch_17_confusion_matrices.json (deflated 90%)
  adding: output/epoch_18_confusion_matrices.json (deflated 90%)
  adding: output/epoch_19_confusion_matrices.json (deflated 90%)
  adding: output/epoch_1_confusion_matrices.json (deflated 89%)
  adding: output/epoch_20_confusion_matrices.json (deflated 90%)
  adding: output/epoch_2_confusion_matrices.json (deflated 89%)
  adding: output/epoch_3_confusion_matrices.json (deflated 89%)
  adding: output/epoch_4_confusion_matrices.json (deflated 89%)
  adding: output/epoch_5_conf