In [ ]:
!git clone --branch dawid/transformers https://github.com/dawidsroczyk/Deep-Learning.git
!mv Deep-Learning/transformers/* .
!gdown 1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
!gdown 1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
!gdown 1GMYLTBi2J0z8tFkDe0sHvw284C4D9Ru5
!rm unknown.pt
!gdown 1hq1OAnSpFCsRJi3E3clpNLfDxhOHpE4H
!mkdir models
!mkdir output

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 2404, done.
remote: Counting objects: 100% (945/945), done.
remote: Compressing objects: 100% (515/515), done.
remote: Total 2404 (delta 496), reused 873 (delta 429), pack-reused 1459 (from 3)
Receiving objects: 100% (2404/2404), 98.03 MiB | 17.41 MiB/s, done.
Resolving deltas: 100% (1135/1135), done.
Downloading...
From (original): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L
From (redirected): https://drive.google.com/uc?id=1zXnV-209gkJSC2kfdOHfAttBLNtzKd4L&confirm=t&uuid=730cf99c-d968-411a-8f2f-368cc13fc9fd
To: /content/test.pt
100% 321M/321M [00:05<00:00, 60.8MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc
From (redirected): https://drive.google.com/uc?id=1kk9KX2crJvb5YzuF2OBMkLLE0vbOG8tc&confirm=t&uuid=b7a9e06b-21d7-4734-8d46-0dc05d2bc8a7
To: /content/train.pt
100% 1.28G/1.28G [00:19<00:00, 64.7MB/s]
Downloading...
From: https://drive.google.com/u

In [ ]:
from batch_ast import train_ast

In [ ]:
!rm -rf models
!rm -rf output
!mkdir models
!mkdir output

In [ ]:
!mkdir models_bs32
!mkdir output_bs32
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs32',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs32',
    random_seed=123,
    batch_size=32
)

mkdir: cannot create directory ‘models_bs32’: File exists
mkdir: cannot create directory ‘output_bs32’: File exists


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 712
100 / 712
200 / 712
300 / 712
400 / 712
500 / 712
600 / 712
700 / 712
Epoch 1/50
Train Loss: 1199.6417 | Train Acc: 0.4118
Test Acc: 0.5060
Train Confusion Matrix:
 [[1882    3    1    1    6    1    0    0    2    1    2   21]
 [  40  780   43  101   47   48  168  102   52  257  165   98]
 [  33   57  705   77  276  329   54   70  106   93   35   50]
 [  28   82   67  690  215   52   70   92  242   68  164  117]
 [  40   45  212  167  879   99   52   60  150   40   46  103]
 [  47   44  226   71  125  962   71  129   66   61   25   73]
 [  45  153   63   70   69   81  703   92   56  317  173   71]
 [  54   89   93  106   82  197  101  746  116   85  122  113]
 [  32   75  119  311  156  112   40  136  563   51  193  109]
 [  32  293   97   52   70   90  327   79   52  563  130   97]
 [  41  162   49  170  105   38  147  101  142  163  654  128]
 [  42  131  116  214  191  132  164  150  208  110  208  254]]
Test Confusion Matrix:
 [[469   0   8   0   0   3   0   0   0   0   0 

In [ ]:
!mkdir models_bs16
!mkdir output_bs16
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs16',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs16',
    random_seed=123,
    batch_size=16
)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 1424
100 / 1424
200 / 1424
300 / 1424
400 / 1424
500 / 1424
600 / 1424
700 / 1424
800 / 1424
900 / 1424
1000 / 1424
1100 / 1424
1200 / 1424
1300 / 1424
1400 / 1424
Epoch 1/50
Train Loss: 2310.8752 | Train Acc: 0.4306
Test Acc: 0.5437
Train Confusion Matrix:
 [[1875    3    3    3    5    2    0    0    5    0    7   17]
 [  45  849   34   84   43   27  127   95   43  273  175  106]
 [  36   54  767   66  271  317   59   77   63   76   32   67]
 [  31   81   47  704  191   42   44  107  254   57  194  135]
 [  39   47  216  162  905   93   44   57  113   32   63  122]
 [  37   48  243   63  110 1009   50  137   54   53   27   69]
 [  46  145   64   71   61   60  713   87   39  338  180   89]
 [  46  110   74  106   63  175   71  864  114   78   86  117]
 [  33   63   86  296  164   79   46  149  562   59  222  138]
 [  34  288   90   61   54   70  330   81   36  600  145   93]
 [  34  165   37  165  103   36  150   79  135  139  718  139]
 [  44  125  110  222  201  113  165  167  2

In [ ]:
!mkdir models_bs1
!mkdir output_bs1
train_ast(
    num_epochs=30,
    # num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs1',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs1',
    random_seed=123,
    batch_size=1
)
!zip -r output_bs1.zip output_bs1/*

TypeError: train_ast() got an unexpected keyword argument 'num_classes'

In [ ]:
!mkdir models_bs2
!mkdir output_bs2
train_ast(
    num_epochs=30,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs2',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs2',
    random_seed=123,
    batch_size=2
)
!zip -r output_bs2.zip output_bs2/*

In [ ]:
!mkdir models_bs4
!mkdir output_bs4
train_ast(
    num_epochs=30,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs4',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs4',
    random_seed=123,
    batch_size=4
)
!zip -r output_bs4.zip output_bs4/*

In [ ]:
!mkdir models_bs8
!mkdir output_bs8
train_ast(
    num_epochs=50,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models_bs8',
    train_data_path='train.pt',
    test_data_path='test.pt',
    unknown_data_path='unknown.pt',
    confusion_matrices_path='output_bs8',
    random_seed=123,
    batch_size=8
)
!zip -r output_bs8.zip output_bs8/*

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:122: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 2848
100 / 2848
200 / 2848
300 / 2848
400 / 2848
500 / 2848
600 / 2848
700 / 2848
800 / 2848
900 / 2848
1000 / 2848
1100 / 2848
1200 / 2848
1300 / 2848
1400 / 2848
1500 / 2848
1600 / 2848
1700 / 2848
1800 / 2848
1900 / 2848
2000 / 2848
2100 / 2848
2200 / 2848
2300 / 2848
2400 / 2848
2500 / 2848
2600 / 2848
2700 / 2848
2800 / 2848
Epoch 1/50
Train Loss: 4498.2179 | Train Acc: 0.4504
Test Acc: 0.5400
Train Confusion Matrix:
 [[1864    8    3    5    6    2    0    1    1    6    2   22]
 [  34  913   24   62   47   35  137  102   33  269  160   85]
 [  36   48  780   53  282  312   48   93   61   69   32   71]
 [  30   74   34  719  191   36   55  131  258   45  179  135]
 [  56   36  196  151  969   80   41   66   95   30   52  121]
 [  40   50  264   35   99 1036   33  155   43   59   32   54]
 [  38  128   45   65   60   54  766   71   45  321  203   97]
 [  33  106   66  114   53  177   76  936  101   77   58  107]
 [  36   69   59  319  165   78   50  146  606   43  207  119]
 [

In [ ]:
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models',
    train_data_path='train.pt',
    test_data_path='test.pt',
    confusion_matrices_path='output',
    random_seed=123,
    batch_size=16
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:110: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 1304
100 / 1304
200 / 1304
300 / 1304
400 / 1304
500 / 1304
600 / 1304
700 / 1304
800 / 1304
900 / 1304
1000 / 1304
1100 / 1304
1200 / 1304
1300 / 1304
Epoch 1/50
Train Loss: 1902.7883 | Train Acc: 0.4813
Test Acc: 0.6126
Train Confusion Matrix:
 [[1883    2    3    4   11    3    0    5    6    2    1]
 [  46  854   32   96   49   51  159   90   39  331  154]
 [  37   64  810   69  256  302   53   64   85   90   55]
 [  45   94   48  745  221   54   60  125  228   48  219]
 [  52   57  185  192  954   92   70   63  122   32   74]
 [  48   52  284   50  106  978   68  167   61   49   37]
 [  34  157   49   74   55   56  843  112   46  286  181]
 [  41   87   83  139   76  203  137  880  121   60   77]
 [  27   62   77  313  183  109   59  178  593   41  255]
 [  42  324   81   54   64   84  306   73   25  698  131]
 [  35  157   43  172  123   36  153   91  168  120  802]]
Test Confusion Matrix:
 [[480   0   0   0   0   0   0   0   0   0   0]
 [  7 324  13  13  15   3   1  37   6  

In [ ]:
!zip -r output_bs16.zip output/*

  adding: output/epoch_10_confusion_matrices.json (deflated 89%)
  adding: output/epoch_11_confusion_matrices.json (deflated 89%)
  adding: output/epoch_12_confusion_matrices.json (deflated 89%)
  adding: output/epoch_13_confusion_matrices.json (deflated 89%)
  adding: output/epoch_14_confusion_matrices.json (deflated 89%)
  adding: output/epoch_15_confusion_matrices.json (deflated 89%)
  adding: output/epoch_16_confusion_matrices.json (deflated 89%)
  adding: output/epoch_17_confusion_matrices.json (deflated 89%)
  adding: output/epoch_18_confusion_matrices.json (deflated 90%)
  adding: output/epoch_19_confusion_matrices.json (deflated 90%)
  adding: output/epoch_1_confusion_matrices.json (deflated 87%)
  adding: output/epoch_20_confusion_matrices.json (deflated 90%)
  adding: output/epoch_21_confusion_matrices.json (deflated 90%)
  adding: output/epoch_22_confusion_matrices.json (deflated 90%)
  adding: output/epoch_23_confusion_matrices.json (deflated 90%)
  adding: output/epoch_24_

In [ ]:
train_ast(
    num_epochs=50,
    num_classes=11,
    lr=1e-5,
    weight_decay=0.05,
    model_path='models',
    train_data_path='train.pt',
    test_data_path='test.pt',
    confusion_matrices_path='output',
    random_seed=123,
    batch_size=32
)

{'silence': 0, 'yes': 1, 'off': 2, 'down': 3, 'on': 4, 'up': 5, 'right': 6, 'stop': 7, 'go': 8, 'left': 9, 'no': 10}


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/transformer.py:385: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(
/content/batch_ast.py:110: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()


0 / 652
100 / 652
200 / 652
300 / 652
400 / 652
500 / 652
600 / 652
Epoch 1/50
Train Loss: 1006.4810 | Train Acc: 0.4506
Test Acc: 0.5565
Train Confusion Matrix:
 [[1879    0    5    3   15    4    0    2   11    0    1]
 [  40  746   51  114   51   50  202   88   48  355  156]
 [  36   72  777   78  286  298   47   72   87   92   40]
 [  37   92   45  720  254   63   77  132  239   45  183]
 [  41   55  248  217  870  103   57   66  134   33   69]
 [  47   52  272   68  131  900   72  175   96   58   29]
 [  46  178   47   98   53   70  747  112   53  290  199]
 [  32   89   73  165   76  205  130  835  146   63   90]
 [  29   48   75  319  205  103   68  174  581   39  256]
 [  35  345   77   70   78  101  316   73   39  630  118]
 [  30  177   40  180  120   55  203   90  166  123  716]]
Test Confusion Matrix:
 [[469   0   0   0  11   0   0   0   0   0   0]
 [ 48 277   3   8  19   5   4  24   0  81   7]
 [ 38  10 167   6 142  52   1  37   2  17   0]
 [ 65   6   1 258  66   0   2  41